/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as CompromissosRouteImport } from './routes/compromissos'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as LimitesRouteImport } from './routes/limites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompromissosRoute = CompromissosRouteImport.update({
  id: '/compromissos',
  path: '/compromissos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitesRoute = LimitesRouteImport.update({
  id: '/limites',
  path: '/limites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/compromissos': typeof CompromissosRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/dividas': typeof DividasRoute
  '/investimentos': typeof InvestimentosRoute
  '/limites': typeof LimitesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/compromissos': typeof CompromissosRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/dividas': typeof DividasRoute
  '/investimentos': typeof InvestimentosRoute
  '/limites': typeof LimitesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/compromissos': typeof CompromissosRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/dividas': typeof DividasRoute
  '/investimentos': typeof InvestimentosRoute
  '/limites': typeof LimitesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cartoes'
    | '/compromissos'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/diagnostico'
    | '/dividas'
    | '/investimentos'
    | '/limites'
    | '/login'
    | '/metas'
    | '/movimentacoes'
    | '/recuperar-senha'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cartoes'
    | '/compromissos'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/diagnostico'
    | '/dividas'
    | '/investimentos'
    | '/limites'
    | '/login'
    | '/metas'
    | '/movimentacoes'
    | '/recuperar-senha'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/cartoes'
    | '/compromissos'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/diagnostico'
    | '/dividas'
    | '/investimentos'
    | '/limites'
    | '/login'
    | '/metas'
    | '/movimentacoes'
    | '/recuperar-senha'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CartoesRoute: typeof CartoesRoute
  CompromissosRoute: typeof CompromissosRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DividasRoute: typeof DividasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  LimitesRoute: typeof LimitesRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compromissos': {
      id: '/compromissos'
      path: '/compromissos'
      fullPath: '/compromissos'
      preLoaderRoute: typeof CompromissosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limites': {
      id: '/limites'
      path: '/limites'
      fullPath: '/limites'
      preLoaderRoute: typeof LimitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CartoesRoute: CartoesRoute,
  CompromissosRoute: CompromissosRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DividasRoute: DividasRoute,
  InvestimentosRoute: InvestimentosRoute,
  LimitesRoute: LimitesRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
